# Generated by Django 5.1.3 on 2024-11-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_op', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeViewModel',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Person_Name', models.CharField(default='Null', max_length=500)),
                ('Salary', models.IntegerField(default=0)),
                ('Bonus', models.IntegerField(default=0)),
                ('Role', models.CharField(default='Null', max_length=500)),
                ('Department', models.CharField(default='Null', max_length=500)),
                ('Location', models.CharField(default='Null', max_length=500)),
                ('HireDate', models.CharField(default='Null', max_length=500)),
                ('Total_Absent', models.IntegerField(default=0)),
                ('Current_Status', models.CharField(default='Null', max_length=500)),
                ('Profile_Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
