# Generated by Django 5.1.3 on 2024-11-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_op', '0002_employeeviewmodel_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeviewmodel',
            name='Download_Link',
            field=models.CharField(default='Null', max_length=500),
        ),
    ]
