# Generated by Django 5.1.3 on 2024-11-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_op', '0003_employeeviewmodel_download_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeviewmodel',
            name='Download_Link',
        ),
    ]
